export const gptResponses: string[] = [
    "That's a great question!",
    "Let me think about that for a moment.",
    "Sure, I can help with that.",
    "Could you clarify your request a bit more?",
    "Here’s what I found on that topic.",
    "I’ll do my best to assist you.",
    "I can explain that in detail.",
    "What specific part would you like to focus on?",
    "Let me provide an example.",
    "Here’s one way to look at it.",
    "That's an interesting point.",
    "Let's break this down step by step.",
    "I'm happy to help!",
    "It sounds like you're asking about...",
    "Let me check that for you.",
    "Good question! Here's an answer.",
    "Let’s dive deeper into this.",
    "I can elaborate if you'd like.",
    "Here’s some context to consider.",
    "It might help to think about it this way.",
    "You’re on the right track!",
    "Let me summarize that for you.",
    "That’s quite insightful!",
    "I see where you’re coming from.",
    "I can explain it a bit differently if needed.",
    "This concept can be tricky.",
    "That’s a common misconception.",
    "Here’s how it works.",
    "Let me give you a breakdown.",
    "What you're asking makes sense!",
    "Let’s approach this another way.",
    "I'm here to help clarify.",
    "That’s a valid question.",
    "There are several factors to consider.",
    "Here's a simpler explanation.",
    "I’ll walk you through it.",
    "I can expand on that.",
    "Let's explore that topic.",
    "That’s a frequently asked question.",
    "I understand your confusion.",
    "Here’s how we can tackle that.",
    "This may seem complex, but I’ll simplify it.",
    "Let’s break that into smaller parts.",
    "I’ve got an idea for how to approach this.",
    "I think I can help explain this more clearly.",
    "This should clear things up.",
    "That’s a really good observation.",
    "It’s helpful to look at it from a different angle.",
    "I'll walk you through the process.",
    "Let me see if I understand you correctly.",
    "This might take some time to explain.",
    "Let's think through this together.",
    "I believe this is what you're looking for.",
    "The key point here is...",
    "I'll clarify that for you.",
    "Let me approach it from a different angle.",
    "Here's a breakdown of what you need to know.",
    "Let’s explore that idea a bit further.",
    "I think you’re asking about...",
    "I’ll explain it as clearly as I can.",
    "I can offer some insights on this.",
    "That’s an important distinction.",
    "Here’s another perspective.",
    "It’s good to understand it this way.",
    "Here’s something you might not have considered.",
    "Let’s take this step by step.",
    "You might find this explanation helpful.",
    "This is a multi-step process.",
    "Here’s the gist of it.",
    "That’s an excellent point to bring up.",
    "It's helpful to consider this aspect as well.",
    "Here's what I would suggest.",
    "Let me break this down for you.",
    "This is how I would explain it.",
    "I can definitely clarify that.",
    "It’s essential to grasp this concept.",
    "I’m happy to explain more!",
    "That’s worth noting!",
    "I can frame that differently.",
    "You could also think of it this way.",
    "Let me rephrase that for clarity.",
    "I’ve got more information on that.",
    "It’s helpful to understand this first.",
    "That’s a question with several layers.",
    "Here’s the important thing to remember.",
    "Let’s analyze this point.",
    "Here's a way to think about it.",
    "It’s a good idea to consider this too.",
    "I’ll explain this in more depth.",
    "This explanation should help.",
    "Let's break this concept down.",
    "Here’s something to keep in mind.",
    "You might also be wondering about this.",
    "It's a bit tricky, but I’ll simplify it.",
    "This might help clarify the issue.",
    "I see how that can be confusing.",
    "I can give you some more details.",
    "Here’s a way to approach this.",
    "Let’s discuss the details.",
    "This could be looked at in different ways.",
    "I'll explain it in simple terms.",
    "Here’s a quick explanation.",
    "I believe this should answer your question.",
    "That’s a topic I can help with.",
    "You’re absolutely right!",
    "Let me elaborate on that point."
];
